# Generated by Django 3.1.6 on 2021-02-07 21:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.TextField(verbose_name='Имя автора')),
                ('birth_year', models.SmallIntegerField(verbose_name='Год рожения')),
                ('country', models.CharField(max_length=2, verbose_name='Страна')),
            ],
        ),
        migrations.CreateModel(
            name='Friend',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.TextField(verbose_name='Имя друга')),
                ('address', models.TextField(verbose_name='Адрес')),
                ('phone', models.TextField(verbose_name='Телефон')),
            ],
        ),
        migrations.CreateModel(
            name='Publisher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(verbose_name='Название')),
                ('address', models.TextField(verbose_name='Юридический адрес')),
                ('web', models.TextField(verbose_name='Web-сайт')),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ISBN', models.CharField(max_length=13, verbose_name='Международный стандартный книжный номер')),
                ('title', models.TextField(verbose_name='Название')),
                ('description', models.TextField(verbose_name='Аннотация')),
                ('year_release', models.SmallIntegerField(verbose_name='Год издания')),
                ('copy_count', models.SmallIntegerField(null=True, verbose_name='Число копий')),
                ('price', models.DecimalField(decimal_places=2, max_digits=12, null=True, verbose_name='Цена')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='book_photo', verbose_name='Изображение книги')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='book_author', to='home_library.author', verbose_name='Автор')),
                ('friends', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='book_friend', to='home_library.friend', verbose_name='Должник')),
                ('publisher', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='book_publisher', to='home_library.publisher', verbose_name='Издательство')),
            ],
        ),
    ]
