# Generated by Django 2.2.6 on 2021-02-08 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_library', '0002_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='photo',
            field=models.ImageField(blank=True, default='user_photo/user.jpg', null=True, upload_to='user_photo', verbose_name='Фотография'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='age',
            field=models.IntegerField(verbose_name='Дата рождения'),
        ),
    ]
