# Generated by Django 3.1.6 on 2021-02-08 22:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_library', '0003_auto_20210208_2243'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='age',
            field=models.DateField(default=datetime.date.today, verbose_name='Дата рождения'),
        ),
    ]
