# Generated by Django 3.1.6 on 2021-02-09 00:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home_library', '0005_auto_20210208_2337'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
